version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: emojigen/docker-web-main-obsolete
    steps:
      - checkout
      - run:
          name: Notify if in master
          command: |
            if [ "${CIRCLE_BRANCH}" == "v1" ]; then
              scripts/notify/start-test.sh
            fi
      - restore_cache:
          key: Emoji-Web-{{ checksum "yarn.lock" }}-{{ checksum "requirements.txt" }}
      - run:
          name: System information
          command: |
            python3 --version
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
      - run:
          name: Install dependencies (Python)
          command: pip3 install --extra-index-url https://repo.fury.io/emoji-gen/ -r requirements.txt
      - run:
          name: Install dependencies (Node)
          command: yarn
      - run:
          name: Test (Node)
          command: |
            yarn test
            yarn run build
            if [ $CIRCLE_BRANCH = 'v1' ]; then scripts/test/git-status.sh; fi
      - save_cache:
          key: Emoji-Web-{{ checksum "yarn.lock" }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
            - ~/.cache/pip/
      - run:
          name: Notify if in master
          command: |
            if [ "${CIRCLE_BRANCH}" == "v1" ]; then
              scripts/notify/end-test.sh
            fi
      - deploy:
          name: Deploy to Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "v1" ]; then
              scripts/deploy.sh
            fi
